import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

import { Args, Flags } from '@oclif/core';

import { clientDir, readClientConfig } from '@upriver/core';

import { BaseCommand } from '../base-command.js';
import { generatePin, hashPin } from '../admin/pin.js';
import { readState, writeState } from '../admin/state.js';

export default class AdminDeploy extends BaseCommand {
  static override description =
    'F05 — set up the natural-language admin for a client. Copies issue templates, label manifest, and the optional Vercel form into clients/<slug>/admin/. Optionally invokes `gh` and `vercel` to apply them remotely.';

  static override examples = [
    '<%= config.bin %> admin-deploy littlefriends --repo=lifeupriver/littlefriends-site --client-form=true',
    '<%= config.bin %> admin-deploy audreys --repo=lifeupriver/audreys-site --no-deploy',
  ];

  static override args = {
    slug: Args.string({ description: 'Client slug', required: true }),
  };

  static override flags = {
    repo: Flags.string({
      description: 'GitHub repo for the client site, format owner/repo. Required.',
      required: true,
    }),
    'client-form': Flags.string({
      description: 'Whether to set up the Vercel client form. true=copy template into admin/form/.',
      options: ['true', 'false'],
      default: 'true',
    }),
    'form-domain': Flags.string({
      description: 'Custom subdomain for the form deploy. Documented in admin/OPERATOR_GUIDE.md.',
    }),
    'form-pin': Flags.string({
      description: '6-digit PIN to require on the form. Random PIN generated when omitted.',
    }),
    'no-deploy': Flags.boolean({
      description: 'Build local files only; do not invoke gh/vercel.',
      default: false,
    }),
    force: Flags.boolean({ description: 'Overwrite existing admin files.', default: false }),
  };

  async run(): Promise<void> {
    const { args, flags } = await this.parse(AdminDeploy);
    const { slug } = args;
    const dir = clientDir(slug);
    if (!existsSync(dir)) this.error(`Client directory not found: ${dir}`);

    const config = readClientConfig(slug);
    const adminDir = join(dir, 'admin');
    if (existsSync(adminDir) && !flags.force) {
      this.error(`Admin already deployed at ${adminDir}. Pass --force to regenerate.`);
    }
    mkdirSync(adminDir, { recursive: true });

    const templateDir = resolveTemplateDir();
    if (!existsSync(templateDir)) {
      this.error(`Admin template not found at ${templateDir}.`);
    }

    // PIN handling: CSPRNG-generated, shown ONCE in this terminal, and only
    // the scrypt hash is written to disk. Artifacts under clients/<slug>/
    // sync-push to the shared bucket, so no file may carry the plaintext.
    const pin = flags['form-pin'] ?? generatePin();
    const pinHash = hashPin(pin);
    const replacements: Record<string, string> = {
      APP_SLUG: slug,
      CLIENT_NAME: config.name ?? slug,
      GITHUB_REPO: flags.repo,
    };

    // Copy GitHub assets to admin/.github/ (operator commits these to the repo).
    const ghSrc = join(templateDir, 'github');
    const ghDest = join(adminDir, '.github');
    copyTreeWithSubst(ghSrc, ghDest, replacements);

    // Copy Vercel form to admin/form/ if requested.
    if (flags['client-form'] === 'true') {
      const formSrc = join(templateDir, 'form');
      const formDest = join(adminDir, 'form');
      copyTreeWithSubst(formSrc, formDest, replacements);
      // Per-client env artifact: carries the PIN HASH only. The plaintext PIN
      // is printed once to the operator's terminal below and exists nowhere
      // else.
      const lines = [
        `# Operator: copy to .env.local / the Vercel project env.`,
        `GITHUB_REPO_TARGET=${flags.repo}`,
        `# Set GITHUB_PAT to a fine-grained PAT with Issues: read+write on this repo.`,
        `GITHUB_PAT=`,
        `# scrypt hash of the form PIN (generated by admin-deploy; PIN itself was`,
        `# shown once at deploy time — rotate with \`upriver admin-rotate-pin ${slug}\`).`,
        `FORM_PIN_HASH=${pinHash}`,
        `NEXT_PUBLIC_CLIENT_NAME=${config.name ?? slug}`,
        ``,
      ];
      writeFileSync(join(formDest, '.env.local.example'), lines.join('\n'), 'utf8');
    }

    // Operator + client guides. Note: renderOperatorGuide never receives the
    // plaintext PIN — the guide syncs to the shared bucket.
    writeFileSync(
      join(adminDir, 'OPERATOR_GUIDE.md'),
      renderOperatorGuide(
        slug,
        flags.repo,
        flags['client-form'] === 'true',
        flags['form-domain'],
        readTemplateLabels(join(templateDir, 'github', 'labels.json')),
      ),
      'utf8',
    );
    writeFileSync(
      join(adminDir, 'CLIENT_GUIDE.md'),
      renderClientGuide(config.name ?? slug, flags['client-form'] === 'true'),
      'utf8',
    );

    // Persist state.
    const state = readState(dir, slug);
    state.github_repo = flags.repo;
    state.form_pin_set = flags['client-form'] === 'true';
    state.deployed_at = new Date().toISOString();
    state.paused = false;
    writeState(dir, state);

    this.log('');
    this.log(`Wrote admin scaffolding to ${adminDir}/`);
    this.log(`  GitHub assets to commit: ${join(adminDir, '.github')}/`);
    if (flags['client-form'] === 'true') {
      this.log(`  Vercel form template: ${join(adminDir, 'form')}/`);
      this.log('');
      this.log(`  Form PIN: ${pin}`);
      this.log('  ^ Shown ONCE, right here. It is not written to any file — only the');
      this.log('    scrypt hash went into form/.env.local.example (FORM_PIN_HASH).');
      this.log(`    Share the PIN with the client; rotate with \`upriver admin-rotate-pin ${slug}\`.`);
    }
    this.log('');

    if (!flags['no-deploy']) {
      this.applyRemote();
    } else {
      this.log('--no-deploy passed; remote setup skipped. Run the gh commands in OPERATOR_GUIDE.md when ready.');
    }
  }

  private applyRemote(): void {
    const ghAvailable = spawnSync('gh', ['--version'], { stdio: 'ignore' }).status === 0;
    if (!ghAvailable) {
      this.warn('`gh` CLI not on PATH; skipping label/template push. See OPERATOR_GUIDE.md for manual steps.');
      return;
    }
    this.log('`gh` CLI detected. Operator should run the commands in OPERATOR_GUIDE.md to push labels and issue templates to the repo. Skipping automatic push to avoid surprising actions on the production repo.');
  }
}

function resolveTemplateDir(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  return join(here, '..', '..', '..', 'admin-template', 'template');
}

function copyTreeWithSubst(srcDir: string, destDir: string, replacements: Record<string, string>): void {
  if (!existsSync(srcDir)) return;
  mkdirSync(destDir, { recursive: true });
  for (const entry of readdirSync(srcDir)) {
    const src = join(srcDir, entry);
    const dest = join(destDir, entry);
    if (statSync(src).isDirectory()) {
      copyTreeWithSubst(src, dest, replacements);
      continue;
    }
    if (/\.(png|jpg|jpeg|webp|ico|woff2?)$/i.test(entry)) {
      copyFileSync(src, dest);
      continue;
    }
    const raw = readFileSync(src, 'utf8');
    const out = raw.replace(/\{\{([A-Z_]+)\}\}/g, (m, key) => replacements[key] ?? m);
    writeFileSync(dest, out, 'utf8');
  }
}

interface LabelEntry {
  name: string;
  color: string;
  description: string;
}

/** Parse the template's labels.json so the guide can emit literal `gh label
 * create` lines (a previous version embedded a jq loop with broken quoting). */
function readTemplateLabels(path: string): LabelEntry[] {
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as unknown;
    if (!Array.isArray(parsed)) return [];
    return parsed.filter(
      (l): l is LabelEntry =>
        typeof l === 'object' &&
        l !== null &&
        typeof (l as LabelEntry).name === 'string' &&
        typeof (l as LabelEntry).color === 'string' &&
        typeof (l as LabelEntry).description === 'string',
    );
  } catch {
    return [];
  }
}

function renderOperatorGuide(
  slug: string,
  repo: string,
  formEnabled: boolean,
  formDomain: string | undefined,
  labels: LabelEntry[],
): string {
  const sections: string[] = [];
  sections.push(`# Admin operator guide: ${slug}`);
  sections.push('');
  sections.push('## What got generated');
  sections.push('');
  sections.push('This directory contains everything you need to wire the natural-language admin for ' + slug + ':');
  sections.push('');
  sections.push('- `.github/ISSUE_TEMPLATE/change-request.yml` — GitHub issue template');
  sections.push('- `.github/labels.json` — labels the bot expects');
  if (formEnabled) sections.push('- `form/` — Next.js single-page client form (deploy to Vercel)');
  sections.push('- `state.json` — local state file the CLI uses');
  sections.push('');
  sections.push('## One-time GitHub setup');
  sections.push('');
  sections.push('From the client site repo:');
  sections.push('');
  sections.push('```bash');
  sections.push('# Copy the issue template into the repo');
  sections.push('mkdir -p .github/ISSUE_TEMPLATE');
  sections.push(`cp $UPRIVER_HOME/clients/${slug}/admin/.github/ISSUE_TEMPLATE/change-request.yml .github/ISSUE_TEMPLATE/`);
  sections.push('');
  sections.push('# Create the labels the bot uses');
  for (const label of labels) {
    sections.push(`gh label create "${label.name}" --color "${label.color}" --description "${label.description}" --force`);
  }
  sections.push('');
  sections.push('# Register the webhook on the worker. The endpoint is served by');
  sections.push('# packages/worker/src/serve.ts (POST /webhook) and is live by default;');
  sections.push('# the secret must equal the worker\'s GITHUB_WEBHOOK_SECRET Fly secret.');
  sections.push('# Only the Issues event is consumed; everything else is ignored.');
  sections.push(`gh api repos/${repo}/hooks \\`);
  sections.push(`  -f name=web \\`);
  sections.push(`  -f config[url]=https://upriver-worker.fly.dev/webhook \\`);
  sections.push(`  -f config[content_type]=json \\`);
  sections.push(`  -f config[secret]="$GITHUB_WEBHOOK_SECRET" \\`);
  sections.push(`  -F events[]=issues`);
  sections.push('');
  sections.push('git add .github && git commit -m "chore: set up Upriver admin (F05)"');
  sections.push('```');
  sections.push('');
  sections.push('## Activate the repo in the allowlist');
  sections.push('');
  sections.push('The worker processes a webhook only when `client_admins` has a matching,');
  sections.push('active row. Until then every delivery is ignored. In the Supabase SQL editor:');
  sections.push('');
  sections.push('```sql');
  sections.push(`update public.client_admins`);
  sections.push(`   set repo_full_name = '${repo}', webhook_active = true`);
  sections.push(` where slug = '${slug}';`);
  sections.push('```');
  sections.push('');
  sections.push(`To pause the bot later: set \`admin_paused = true\` (or \`upriver admin-pause ${slug}\` for local runs).`);
  sections.push('');
  if (formEnabled) {
    sections.push('## One-time Vercel form deploy');
    sections.push('');
    sections.push('```bash');
    sections.push(`cd $UPRIVER_HOME/clients/${slug}/admin/form`);
    sections.push('npm install');
    sections.push('npm run build');
    sections.push('npx vercel --prod');
    sections.push('```');
    sections.push('');
    sections.push('Then on the Vercel project, set environment variables:');
    sections.push('');
    sections.push(`- \`GITHUB_REPO_TARGET=${repo}\``);
    sections.push('- `GITHUB_PAT=<fine-grained PAT, Issues: read+write on the repo>`');
    sections.push('- `FORM_PIN_HASH=<copy from form/.env.local.example — written at deploy>`');
    sections.push(`- \`NEXT_PUBLIC_CLIENT_NAME=<display name>\``);
    sections.push('');
    sections.push('The PIN is mandatory: the form returns 503 until FORM_PIN_HASH is set.');
    sections.push('');
    if (formDomain) sections.push(`Form domain: \`${formDomain}\`.`);
    sections.push('');
  }
  sections.push('## Day-to-day');
  sections.push('');
  sections.push('```bash');
  sections.push(`# Run a change request locally (test without a webhook)`);
  sections.push(`upriver admin-process ${slug} \\`);
  sections.push(`  --repo-dir=PATH-TO-LOCAL-CLONE \\`);
  sections.push(`  --issue-number=42 \\`);
  sections.push(`  --issue-title="..." \\`);
  sections.push(`  --issue-body-file=./issue.md`);
  sections.push('');
  sections.push(`upriver admin-pause ${slug}`);
  sections.push(`upriver admin-status ${slug}`);
  sections.push(`upriver admin-rotate-pin ${slug}`);
  sections.push('```');
  sections.push('');
  sections.push('## What the bot does');
  sections.push('');
  sections.push('When an issue with the `change-request` label is opened (or labeled):');
  sections.push('');
  sections.push('1. GitHub POSTs to the worker\'s `/webhook`; the worker verifies the HMAC signature and replay-guards the delivery.');
  sections.push('2. The `admin-webhook` Inngest function checks `client_admins`: the repo must be allowlisted (`webhook_active`) and not paused. The repo to clone always comes from that row, never from the webhook payload.');
  sections.push('3. It shallow-clones the repo and runs `upriver admin-process` in a sandboxed subprocess (no GitHub or Supabase credentials in its environment).');
  sections.push('4. The diff goes through the voice-check (banned words, em dashes, required markers).');
  sections.push('5. If the voice-check passes and files changed, the worker pushes `admin/issue-<n>` and opens a DRAFT PR labeled `pending-review`. It never merges — a human always reviews.');
  sections.push('6. If blocked (voice-check failure, missing assets, no diff), the bot comments on the issue and labels it `needs-operator`.');
  sections.push('7. If `ADMIN_OPERATOR_SLACK_WEBHOOK` is configured on the worker, you get a one-line Slack summary either way.');
  sections.push('');
  sections.push('## Form PIN');
  sections.push('');
  sections.push(
    `The PIN is shown once at deploy — it is not stored anywhere in plaintext. Rotate with \`upriver admin-rotate-pin ${slug}\` whenever the client asks (prints a new PIN once and the hash to set on Vercel).`,
  );
  sections.push('');
  return sections.join('\n');
}

function renderClientGuide(clientName: string, formEnabled: boolean): string {
  const lines: string[] = [];
  lines.push(`# How to request changes to the ${clientName} site`);
  lines.push('');
  lines.push('## The short version');
  lines.push('');
  lines.push(
    formEnabled
      ? 'Visit the request form (operator: paste the URL here once you have it). Type what you want changed. We will get to it within a day.'
      : 'Email Upriver with the change you want. We will track it from there.',
  );
  lines.push('');
  lines.push('## What to include');
  lines.push('');
  lines.push('- A sentence about what should change.');
  lines.push('- A note about where on the site, if you know.');
  lines.push('- Photos or files if relevant. Drag and drop into the form, or send links.');
  lines.push('');
  lines.push('## What happens next');
  lines.push('');
  lines.push('Once we get your request, you will see a confirmation. Within a few minutes our system will respond with what we understood. If we got it wrong, just reply with the correction. If we got it right, we make the change and send you a preview link to look at.');
  lines.push('');
  lines.push('## What we will not do automatically');
  lines.push('');
  lines.push('If a change requires us to write something we do not have facts to back up, or to publish a price or a quote we cannot verify, we will pause and ask you. We will never make up facts about your business.');
  lines.push('');
  return lines.join('\n');
}
