import { execSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { Args, Flags } from '@oclif/core';
import { BaseCommand } from '../../base-command.js';
import { updateClientConfig } from '@upriver/core';
import { resolveScaffoldPaths } from '../../scaffold/template-writer.js';

const REGION = 'us-east-1';

export default class ScaffoldSupabase extends BaseCommand {
  static override description = 'Create Supabase project, run migrations, write env vars (dry-run by default)';

  static override args = {
    slug: Args.string({ description: 'Client slug', required: true }),
  };

  static override flags = {
    commit: Flags.boolean({ description: 'Execute — without this flag only prints what would happen' }),
    org: Flags.string({ description: 'Supabase organization id', env: 'SUPABASE_ORG_ID' }),
    region: Flags.string({ description: 'Supabase region', default: REGION }),
  };

  async run(): Promise<void> {
    const { args, flags } = await this.parse(ScaffoldSupabase);
    const { slug } = args;
    const { clientDir, repoDir } = resolveScaffoldPaths(slug);

    const migrationsDir = join(repoDir, 'supabase', 'migrations');
    if (!existsSync(migrationsDir)) {
      this.error(`No supabase/migrations/ folder at ${migrationsDir}. Run "upriver scaffold ${slug}" first.`);
    }
    const migrations = readdirSync(migrationsDir).filter((f) => f.endsWith('.sql')).sort();

    const projectName = `upriver-${slug}`;

    if (!flags.commit) {
      this.log('\n[dry-run] upriver scaffold supabase would:');
      this.log(`  1. POST https://api.supabase.com/v1/projects to create "${projectName}" (region=${flags.region})`);
      this.log(`  2. Wait for project to become ACTIVE_HEALTHY`);
      this.log(`  3. Apply ${migrations.length} migration(s) via the Management API:`);
      for (const m of migrations) this.log(`       - ${m}`);
      this.log(`  4. Write connection strings to ${join(clientDir, '.env.local')}`);
      this.log(`  5. Update client-config.yaml supabase_project_ref`);
      this.log('\nRun with --commit to execute. Requires SUPABASE_MANAGEMENT_TOKEN env var (and --org or SUPABASE_ORG_ID).');
      return;
    }

    const token = this.requireEnv('SUPABASE_MANAGEMENT_TOKEN');
    const org = flags.org ?? this.requireEnv('SUPABASE_ORG_ID');
    const dbPassword = generatePassword();

    this.log(`\nCreating Supabase project ${projectName}...`);
    const project = await createProject(token, org, projectName, dbPassword, flags.region);
    this.log(`  ref: ${project.id}`);

    this.log('Waiting for project to become healthy...');
    await waitForHealthy(token, project.id);

    this.log(`Applying ${migrations.length} migration(s)...`);
    for (const file of migrations) {
      const sql = readFileSync(join(migrationsDir, file), 'utf8');
      this.log(`  - ${file}`);
      await runQuery(token, project.id, sql);
    }

    this.log('Fetching API keys...');
    const keys = await fetchApiKeys(token, project.id);

    const url = `https://${project.id}.supabase.co`;
    const envBody = [
      `# Generated by upriver scaffold supabase ${slug}`,
      `PUBLIC_SUPABASE_URL=${url}`,
      `PUBLIC_SUPABASE_ANON_KEY=${keys.anon}`,
      `SUPABASE_SERVICE_ROLE_KEY=${keys.serviceRole}`,
      `SUPABASE_DB_PASSWORD=${dbPassword}`,
      `SUPABASE_PROJECT_REF=${project.id}`,
      '',
    ].join('\n');
    mkdirSync(clientDir, { recursive: true });
    writeFileSync(join(clientDir, '.env.local'), envBody, 'utf8');

    updateClientConfig(slug, { supabase_project_ref: project.id });

    this.log(`\nDone. Project ref: ${project.id}`);
    this.log(`  Wrote ${join(clientDir, '.env.local')}`);
    this.log(`  Updated client-config.yaml supabase_project_ref`);
  }
}

interface CreatedProject {
  id: string;
}

async function createProject(
  token: string,
  organizationId: string,
  name: string,
  dbPassword: string,
  region: string,
): Promise<CreatedProject> {
  const res = await fetch('https://api.supabase.com/v1/projects', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      organization_id: organizationId,
      name,
      region,
      db_pass: dbPassword,
      plan: 'free',
    }),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Supabase create project failed (${res.status}): ${body}`);
  }
  return (await res.json()) as CreatedProject;
}

async function waitForHealthy(token: string, ref: string, maxSeconds = 240): Promise<void> {
  const start = Date.now();
  while ((Date.now() - start) / 1000 < maxSeconds) {
    const res = await fetch(`https://api.supabase.com/v1/projects/${ref}`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (res.ok) {
      const data = (await res.json()) as { status?: string };
      if (data.status === 'ACTIVE_HEALTHY') return;
    }
    await sleep(5000);
  }
  throw new Error(`Supabase project ${ref} did not become healthy within ${maxSeconds}s`);
}

async function runQuery(token: string, ref: string, query: string): Promise<void> {
  const res = await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Supabase query failed (${res.status}): ${body}`);
  }
}

interface ApiKeys {
  anon: string;
  serviceRole: string;
}

async function fetchApiKeys(token: string, ref: string): Promise<ApiKeys> {
  const res = await fetch(`https://api.supabase.com/v1/projects/${ref}/api-keys`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) throw new Error(`Supabase api-keys failed (${res.status}): ${await res.text()}`);
  const keys = (await res.json()) as Array<{ name: string; api_key: string }>;
  const anon = keys.find((k) => k.name === 'anon')?.api_key ?? '';
  const serviceRole = keys.find((k) => k.name === 'service_role')?.api_key ?? '';
  return { anon, serviceRole };
}

function generatePassword(): string {
  const bytes = execSync('openssl rand -base64 24').toString('utf8').trim();
  return bytes.replace(/[^a-zA-Z0-9]/g, '').slice(0, 32) || 'pleaseChangeMe1234';
}

function sleep(ms: number): Promise<void> {
  return new Promise((res) => setTimeout(res, ms));
}
