/**
 * Client-specific content for the prototype. Generated by `upriver prototype-app`
 * from the scraped pages and audit-package. Hand-edits here will be overwritten
 * on regenerate.
 */

export interface ServiceItem {
  name: string;
  description: string;
}

export interface TeamMember {
  name: string;
  role: string;
}

export interface ContactInfo {
  phone: string | null;
  email: string | null;
  address: string | null;
  hours: string | null;
}

export interface ClientContent {
  brandName: string;
  tagline: string;
  heroImage: string | null;
  about: string;
  services: ServiceItem[];
  team: TeamMember[];
  contact: ContactInfo;
  galleryImages: string[];
}

export const content: ClientContent = /* CONTENT_PAYLOAD */ {} as unknown as ClientContent;
