/**
 * Design tokens for this client's prototype. Generated by `upriver prototype-app`
 * from the rebuilt site's design tokens. Hand-edits here are fine — they will
 * be overwritten on regenerate.
 */
export const theme = {
  colors: {
    primary: '{{BRAND_PRIMARY}}',
    accent: '{{BRAND_ACCENT}}',
    background: '{{BRAND_BACKGROUND}}',
    surface: '{{BRAND_SURFACE}}',
    text: '{{BRAND_TEXT}}',
    muted: '{{BRAND_MUTED}}',
    border: '{{BRAND_BORDER}}',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  fontSize: {
    sm: 14,
    base: 16,
    lg: 20,
    xl: 26,
    xxl: 34,
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 20,
  },
};
